# 配置端口信息
server:
  port: 8001


spring:
  application:
    name: clould-payment-service
  # 配置数据源信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ms_hoxton_sr1_payment?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

# 配置mybatis-plus信息
mybatis-plus:
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
  # 配置类型别名所对应的包名
  type-aliases-package: com.cp.company.pojo
  # 扫描通用枚举类所在的包
  type-enums-package: com.cp.company.enums

# 配置PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
