# 配置端口信息
server:
  port: 80

spring:
  application:
    name: clould-order-service
  # 配置数据源信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ms_hoxton_sr1_order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  # 允许存在多个Feign调用相同服务提供者的接口(默认为false)
  main:
    allow-bean-definition-overriding: true

# 配置服务注册
eureka:
  client:
    # 表示将自己注册进EurekaServer,默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息,默认为true. 单节点无所谓,集群必须设置为true,才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: order80
    prefer-ip-address: true # 访问路径可以显示IP地址
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    lease-renewal-interval-in-seconds: 5
    # Eureka服务端收到最后一次心跳后等待时间上限,单位为秒(默认90秒),超时则剔除该服务
    lease-expiration-duration-in-seconds: 10

# OpenFeign接口超时时间 (OpenFeign默认超时时间1秒)
ribbon:
  # 指定是建立连接所用的时间,适用于网络状况良好的情况下,两端连接所用的时间,单位:毫秒
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到数据资源所用时间,单位:毫秒
  ConnectTimeout: 6000

# 配置OpenFeign日志增强
logging:
  level:
    # feign日志以哪种级别监控哪个feign接口的日志
    com.cp.company.feign.PaymentServiceFeign: debug

feign:
  hystrix:
    # 服务消费端开启Hystrix服务降级
    enabled: true

provider:
  name:
    # 支付服务提供者名称
    payment: CLOULD-PAYMENT-SERVICE

# 配置mybatis-plus信息
mybatis-plus:
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
  # 配置类型别名所对应的包名
  type-aliases-package: com.cp.company.pojo
  # 扫描通用枚举类所在的包
  type-enums-package: com.cp.company.enums

# 配置PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


